# Site settings
title: Your Name
email: Your Email
description: "Your Description"
username: andrechristoga
baseurl: ""
url: ""
paginate: 4
paginate_path: "page/:num/"

# Build settings`
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
rouge: pygments
