# Site settings
title: Jekyll Material
description: "A material design Jekyll theme."
baseurl: "/jekyll-material"
url: "https://christoga.github.io/jekyll-material"
paginate: 4
paginate_path: "page/:num/"
color: indigo-pink

# Author social links
social:
  facebook: username
  twitter: username
  instagram: username
  google_plus: username
  github: username
  email: andrechristoga@gmail.com
  disqus: username

# Build settings
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
rouge: pygments
